### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by NatanRincker** [NatanRincker/clone-tabnews#25]
## Tasks
- [ ] Create a new migration responsible for creating the `user` table
- [ ] Create a model that encapsulates `create` and `update` functions for `users`
- [ ] Create route `/api/v1/users` to make the model accessible through the API
- [ ] Create a `Controller` to allow execution of commands for `user` model
### Polishment
- [ ] Make user migrations run independently of endpoint `api/v1/migrations` (Could need a separate issue)

## Attention Points
- Not create DELETE method for users
- Not create hash for password - This will be handled in the future in a new issue
- When submitting a GET against a user, it should return ALL the data, private data included
