### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by NatanRincker** [NatanRincker/clone-tabnews#26]
## Tasks
- [ ] Create active sesssion in the browser by providing email and password
- [ ] Log session's token in the browser's cookies
- [ ] encrypt user password
- [ ] create endpoint `/api/v1/sessions`
