### ISSUE TITLE
Email System

### ISSUE THREAD

**Issue by NatanRincker** [NatanRincker/clone-tabnews#27]
## Tasks
- [ ] Send email with token to validate user registration
- [ ] Create email catcher to validate email are being sent correctly
- [ ] Implemment last email sent validation on `Orchestrator`
- [ ] Implement `clearInbox` function on `Orchestrator` for tests to start from a default state
