### ISSUE TITLE
Implement Authorization

### ISSUE THREAD

**Issue by NatanRincker** [NatanRincker/clone-tabnews#28]
## Tasks
- [ ] Use `NextConnect` middlewares to inject users in requests
- [ ] Validate if user has permision to execute action against the requested resource;
- [ ] Create an output filter before sending the response

## Attention Points
- Use Resource based access control
- Grant more permissions to a user based on "achievements" like clicking on the email confirmation link
